spring:
    application:
        name: demo2

    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/stu
      driver-class-name: com.mysql.jdbc.Driver

demo2:
    className: Java实训
    count: 11
    teacher: {name: liu, age: 12}

server:
    port: 8080

#mybatis:
#    mapper-locations: classpath:mapper/*.xml
